name: Run every hour

on:
  schedule:
    - cron: '35 * * * *'

jobs:
  cron:
    name: Run every hour
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello, world!"